const STUDENT_TAB = "STUDENT_TAB";
const LIBRARIAN_TAB = "LIBRARIAN_TAB";
const SEARCH_RESULTS = "SEARCH_RESULTS";
const STUDENT_QUERY = "STUDENT_QUERY";
const LIBRARIAN_QUERY = "LIBRARIAN_QUERY";
const CHECKOUT_TAB = "CHECKOUT_TAB";
const CHECKIN_TAB = "CHECKIN_TAB";
const FETCH_BOOK_RESULTS = "FETCH_BOOK_RESULTS";
const FETCH_USER_RESULTS = "FETCH_USER_RESULTS";
const CREATE_USER = "CREATE_USER";
const USER_CREATED = "USER_CREATED"

export default {
    STUDENT_TAB,
    LIBRARIAN_TAB,
    SEARCH_RESULTS,
    STUDENT_QUERY,
    LIBRARIAN_QUERY,
    CHECKOUT_TAB,
    CHECKIN_TAB,
    FETCH_BOOK_RESULTS,
    FETCH_USER_RESULTS,
    CREATE_USER,
    USER_CREATED
}