const STUDENT_TAB = "STUDENT_TAB";
const LIBRARIAN_TAB = "LIBRARIAN_TAB";
const SEARCH_RESULTS = "SEARCH_RESULTS";
const STUDENT_QUERY = "STUDENT_QUERY";
const LIBRARIAN_QUERY = "LIBRARIAN_QUERY";
const CHECKOUT_TAB = "CHECKOUT_TAB";
const FETCH_BOOK_RESULTS = "FETCH_BOOK_RESULTS"
const FETCH_USER_RESULTS = "FETCH_USER_RESULTS"

export default {
    STUDENT_TAB,
    LIBRARIAN_TAB,
    SEARCH_RESULTS,
    STUDENT_QUERY,
    LIBRARIAN_QUERY,
    CHECKOUT_TAB,
    FETCH_BOOK_RESULTS,
    FETCH_USER_RESULTS
}