const STUDENT_TAB = "STUDENT_TAB";
const LIBRARIAN_TAB = "LIBRARIAN_TAB";
const SEARCH_RESULTS = "SEARCH_RESULTS";
const STUDENT_QUERY = "STUDENT_QUERY";
const LIBRARIAN_QUERY = "LIBRARIAN_QUERY";

export default {
    STUDENT_TAB,
    LIBRARIAN_TAB,
    SEARCH_RESULTS,
    STUDENT_QUERY,
    LIBRARIAN_QUERY
}